In [45]:
# install StellarGraph if running on Google Colab
import sys
if 'google.colab' in sys.modules:
  %pip install -q stellargraph[demos]==1.2.

In [77]:
a1=np.loadtxt('/content/002_S_1280_I829304 (1)')
a2=np.loadtxt('/content/002_S_1155_I843517 (1)')
a3=np.loadtxt('/content/002_S_1155_I995512 (1)')
a4=np.loadtxt('/content/002_S_1261_I989328 (1)')
a5=np.loadtxt('/content/002_S_1280_I829304 (1)')


In [78]:
from networkx.algorithms.assortativity.pairs import node_attribute_xy
import numpy as np
import networkx as nx
from stellargraph import StellarGraph

# Define adjacency matrices for undirected graphs
#adj_matrices = [A[0], A[1], A[2], A[3], A[4]]
adj_matrices=[a1,a2,a3,a4,a5]
graphs = []

# Create a StellarGraph object for each adjacency matrix
for adj_matrix in adj_matrices:
    num_nodes = adj_matrix.shape[0]
    # Define nodes as a dictionary of {node ID: attribute dictionary}
    nodes = {i: {"feature": f"feature {i}"} for i in range(num_nodes)}

    # Define edges as a list of (source, target, weight) tuples
    edges = [(i, j, float(adj_matrix[i, j])) for i in nodes for j in nodes if adj_matrix[i, j] == 1]

    # Create a NetworkX graph and add nodes and edges
    nx_graph = nx.Graph()
    nx_graph.add_nodes_from(nodes)
    nx_graph.add_weighted_edges_from(edges)
    #print(nx_graph.nodes()) 
    node_features = {node_id: np.zeros((3,), dtype=np.float32) if adj_matrix[node_id, :].sum() == 0 else np.array([1.0, 1.0, 1.0], dtype=np.float32) for node_id in range(num_nodes)}
  
    #print(node_features)
   # print(nx_graph)
    # Convert NetworkX graph to StellarGraph object
    nx.set_node_attributes(nx_graph, node_features, "features")

    
    graph = StellarGraph.from_networkx(nx_graph, node_features="features")
    #print(graph.node_features())
    graphs.append(graph)
#print(nx_graph.nodes())    


In [ ]:
if np.count_nonzero(A[0]) > 0:
    print("The adjacency matrix has edges.")
else:
    print("The adjacency matrix does not have any edges.")


The adjacency matrix has edges.


In [56]:
#WITHOUT NODE FEATURES STELLAR GENERATOR IS GETTING ERROR SO I USED EQUAL NUMBER OF NODE FEATURES FOR ALL THE NODES
print(graphs[0].node_features())

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1.

In [79]:
print(graphs[0].info())

StellarGraph: Undirected multigraph
 Nodes: 160, Edges: 984

 Node types:
  default: [160]
    Features: float32 vector, length 3
    Edge types: default-default->default

 Edge types:
    default-default->default: [984]
        Weights: all 1 (default)
        Features: none


In [58]:
#print(graph_labels)
import pandas as pd
graph_labels = pd.Series(graph_labels)
label_counts = graph_labels.value_counts()
print(type(graph_labels))
#print(label_counts)


<class 'pandas.core.series.Series'>


In [ ]:
import pandas as pd
summary = pd.DataFrame(
    [(g.number_of_nodes(), g.number_of_edges()) for g in graphs],
    columns=["nodes", "edges"],
)
summary.describe().round(1)

nodes  edges
count    5.0    5.0
mean   160.0  729.0
std      0.0   64.3
min    160.0  650.0
25%    160.0  681.0
50%    160.0  730.0
75%    160.0  787.0
max    160.0  797.0

In [ ]:
graph_labels.value_counts().to_frame()

0
1  3
0  2

In [59]:
import pandas as pd
import numpy as np

import stellargraph as sg
from stellargraph.mapper import PaddedGraphGenerator
from stellargraph.layer import GCNSupervisedGraphClassification
from stellargraph import StellarGraph

from stellargraph import datasets

from sklearn import model_selection
from IPython.display import display, HTML

from tensorflow.keras import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import binary_crossentropy
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf
import matplotlib.pyplot as plt

In [60]:
generator = PaddedGraphGenerator(graphs=graphs)

In [61]:
def create_graph_classification_model(generator):
    gc_model = GCNSupervisedGraphClassification(
        layer_sizes=[64, 64],
        activations=["relu", "relu"],
        generator=generator,
        dropout=0.5,
    )
    x_inp, x_out = gc_model.in_out_tensors()
    predictions = Dense(units=32, activation="relu")(x_out)
    predictions = Dense(units=16, activation="relu")(predictions)
    predictions = Dense(units=1, activation="sigmoid")(predictions)

    # Let's create the Keras model and prepare it for training
    model = Model(inputs=x_inp, outputs=predictions)
    model.compile(optimizer=Adam(0.005), loss=binary_crossentropy, metrics=["acc"])

    return model

In [67]:
epochs = 200  # maximum number of training epochs
folds = 3  # the number of folds for k-fold cross validation
n_repeats = 3  # the number of repeats for repeated k-fold cross validation

In [68]:
es = EarlyStopping(
    monitor="val_loss", min_delta=0, patience=25, restore_best_weights=True
)

In [71]:
def train_fold(model, train_gen, test_gen, es, epochs):
    history = model.fit(
        train_gen, epochs=epochs, validation_data=test_gen, verbose=0, callbacks=[es],
    )
    # calculate performance on the test data and return along with history
    test_metrics = model.evaluate(test_gen, verbose=1)
    test_acc = test_metrics[model.metrics_names.index("acc")]

    return history, test_acc

In [72]:
def get_generators(train_index, test_index, graph_labels, batch_size):
    train_gen = generator.flow(
        train_index, targets=graph_labels.iloc[train_index].values, batch_size=batch_size
    )
    test_gen = generator.flow(
        test_index, targets=graph_labels.iloc[test_index].values, batch_size=batch_size
    )

    return train_gen, test_gen

In [73]:
test_accs = []

stratified_folds = model_selection.RepeatedStratifiedKFold(
    n_splits=folds, n_repeats=n_repeats
).split(graph_labels, graph_labels)

for i, (train_index, test_index) in enumerate(stratified_folds):
    print(f"Training and evaluating on fold {i+1} out of {folds * n_repeats}...")
    train_gen, test_gen = get_generators(
        train_index, test_index, graph_labels, batch_size=2
    )

    model = create_graph_classification_model(generator)

    history, acc = train_fold(model, train_gen, test_gen, es, epochs)

    test_accs.append(acc)

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(


Training and evaluating on fold 1 out of 9...
1/1 [==============================] - 0s 46ms/step - loss: 0.6931 - acc: 0.5000
Training and evaluating on fold 2 out of 9...
1/1 [==============================] - 0s 42ms/step - loss: 0.7257 - acc: 0.5000
Training and evaluating on fold 3 out of 9...
1/1 [==============================] - 0s 42ms/step - loss: 0.6316 - acc: 1.0000
Training and evaluating on fold 4 out of 9...


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(


1/1 [==============================] - 0s 45ms/step - loss: 0.7029 - acc: 0.5000
Training and evaluating on fold 5 out of 9...
1/1 [==============================] - 0s 37ms/step - loss: 0.6977 - acc: 0.5000
Training and evaluating on fold 6 out of 9...
1/1 [==============================] - 0s 37ms/step - loss: 0.6219 - acc: 1.0000
Training and evaluating on fold 7 out of 9...


/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=3.
  warnings.warn(


1/1 [==============================] - 0s 42ms/step - loss: 0.7123 - acc: 0.5000
Training and evaluating on fold 8 out of 9...
1/1 [==============================] - 0s 45ms/step - loss: 0.7023 - acc: 0.5000
Training and evaluating on fold 9 out of 9...
1/1 [==============================] - 0s 41ms/step - loss: 0.6555 - acc: 1.0000


In [74]:
print(
    f"Accuracy over all folds mean: {np.mean(test_accs)*100:.3}% and std: {np.std(test_accs)*100:.2}%"
)

Accuracy over all folds mean: 66.7% and std: 2.4e+01%


In [ ]:
import networkx as nx

# Load the adjacency matrices
A = []
#/graph1.gml
for i in range(5):
    filename = f"/graph{i+1}.gml"
    #print(filename)
    graph = nx.read_gml(filename)
    #print(graph)
    A.append(nx.adjacency_matrix(graph).todense())

# Load the labels
label = []
with open("/labels.txt") as f:
    for line in f:
        label.append(int(line.strip()))


In [ ]:
import numpy as np
import networkx as nx
from stellargraph import StellarGraph

# Define an adjacency matrix for an undirected graph
adj_matrices =[A[0],A[1],A[2],A[3],A[4]]
print(adj_matrices[0])
graphs = []
node_features = {i: np.array([1.0, 1.0, 1.0], dtype=np.float32) for i in range(adj_matrices[0].shape[0])}

# Create a StellarGraph object for each adjacency matrix
for adj_matrix in adj_matrices:
    nodes = {i: {"feature": f"feature {i}"} for i in range(adj_matrix.shape[0])}
    node_features = {node_id: np.array([1.0, 1.0, 1.0], dtype=np.float32) for node_id in nodes.keys()}

    edges = [(i, j, float(adj_matrix[i, j])) for i in nodes for j in nodes if adj_matrix[i, j] == 1]

    nx_graph = nx.Graph()
    nx_graph.add_nodes_from(nodes)
    nx_graph.add_weighted_edges_from(edges)

    graph = StellarGraph.from_networkx(nx_graph, node_features=node_features)
    print(graph.node_features())

    graphs.append(graph)


# for i, adj_matrix in enumerate(adj_matrices):
#     nodes = {i: {"feature": f"feature {i}"} for i in range(adj_matrix.shape[0])}
#     #node_features = {node_id: np.array([1.0, 1.0, 1.0], dtype=np.float32) for node_id in range(adj_matrix.shape[0])}

#     edges = [(i, j, float(adj_matrix[i, j])) for i in nodes for j in nodes if adj_matrix[i, j] == 1]
#     #print(edges)
#     nx_graph = nx.Graph()
#     nx_graph.add_nodes_from(nodes)
#     nx_graph.add_weighted_edges_from(edges)
#    # nx_graph.add_edges_from(edges)
#     node_feature = {node_id: {"dummy_feature": 1} for node_id in nodes}
#     #print(node_features)
# # Convert the NetworkX graph to a StellarGraph object
#     graph = StellarGraph.from_networkx(nx_graph, node_features=node_feature)
#     print(graph.node_features())
#     graph_labels = [0, 1,1,0,1]
#     #graph.set_name(f"Graph{i+1}")
#     graphs.append(graph)
#graphs
#print(node_features)

[[0.00000e+00 0.00000e+00 0.00000e+00 ... 0.00000e+00 0.00000e+00
  0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 ... 1.00000e+00 0.00000e+00
  0.00000e+00]
 [0.00000e+00 0.00000e+00 0.00000e+00 ... 0.00000e+00 0.00000e+00
  0.00000e+00]
 ...
 [0.00000e+00 1.00000e+00 0.00000e+00 ... 0.00000e+00 7.69000e+03
  8.73590e+04]
 [0.00000e+00 0.00000e+00 0.00000e+00 ... 7.69000e+03 0.00000e+00
  4.50382e+05]
 [0.00000e+00 0.00000e+00 0.00000e+00 ... 8.73590e+04 4.50382e+05
  0.00000e+00]]
